language: r
cache: packages
sudo: false
warnings_are_errors: false

notifications:
  slack: min-agricultura:dff7wdgnfp9Sm2TIKiFEvQ5J
      
before_install:
  - cd R/rDOU

r_github_packages:
  - jimhester/covr
  
after_success:
  - Rscript -e 'covr::codecov()'
  
